
[hasura]
  version = 'v2.44.0-ce'

[functions]
  [functions.node]
    version = 22

[auth]
  version = '0.37.1'

  [auth.redirections]
    clientUrl = 'http://localhost:3000'

[postgres]
  version = '16-v5.3.0'

[storage]
  version = '0.6.1'


